### ISSUE TITLE
Nothing works!

### ISSUE THREAD

**Issue by PascalPixel** [nothingsite/nothingsite.github.io#1]
Title says it all..

**Comment by NetOpWibby** [comment]
I am experiencing this issue as well. What could be the reason, please fix.

**Comment by ersanceylan** [comment]
hi @Superpencil @NetOperatorWibby ,
clear your browser cache and see it works!!!!!

**Comment by dnomak** [comment]
@Superpencil @NetOperatorWibby Which browser?

**Comment by PascalPixel** [comment]
Internet Explorer 5.5, I'm running 98SE

**Comment by NetOpWibby** [comment]
@rsncyln @dnomak Even though I am using Opera Developer, I didn't have to pay cash like the earlier versions. Does clear cash exist? Is this the future? Maybe this site uses HTML9. :(

**Comment by drawby** [comment]
all browsers seem to render a nihilistic experience for me. still have to check mobile.

**Comment by LanceTurri** [comment]
@drawby Just checked mobile, same nihilistic experience. Coincidence?

**Comment by madhunandi** [comment]
Open your command prompt and provide the following command.
start http://nothingsite.com/  ;) Hope it works :)

**Comment by PascalPixel** [comment]
Closing this as nothing works.
